version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn clean install
  post_build:
    commands:
    - echo Build completed on `date`
    - mv target/vehicle-listing-0.0.1-SNAPSHOT.war vehicle-listing-0.0.1-SNAPSHOT.war
artifacts:
  files:
  - vehicle-listing-0.0.1-SNAPSHOT.war
  - .ebextensions/**/*